name: webapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  webview_flutter: ^3.0.1
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true

flutter:

  uses-material-design: true
  assets:
    - assets/images/

